version: '3'
services:

  # database:
  #   image: mariadb:latest
  #   restart: always
  #   ports:
  #      - '3306:3306'
  #   environment:
  #      MYSQL_ROOT_PASSWORD: 'root_password'
  #      MYSQL_DATABASE: 'EarthCast'
  #      MYSQL_USER: 'root'
  #      MYSQL_PASSWORD: 'root_password'

  front:
    build: ./frontend
    volumes:
      - ./frontend:/home/node/frontend
    ports:
      - '3001:3000'
    command: npm start

  back:
    build: ./backend
    ports:
       - '8000:8000'
    volumes:
       - ./backend:/backend
    # depends_on:
    #    - mariadb
    command: gunicorn -b 0.0.0.0:8000 myproject.wsgi:application
